version: '3'
services:
  flask:
    build: .
    command: python run.py
    ports:
      - "5001:5000"
    volumes:
      - ./:/flask_servers
  flask2:
    build: .
    command: python app.py
    ports:
      - "5002:5000"
    volumes:
      - ./:/flask_servers

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - flask
      - flask2
